version: '3.9'
services:
  web:
    build:
      context: ../
      dockerfile: ./apps/web/Dockerfile
    command: npm run dev
    working_dir: /app/apps/web
    env_file:
      - ../.env.local
    environment:
      # Use API service for development - Docker internal networking
      - NEXT_PUBLIC_API_URL=http://api:8000/api
      # Alternative: Use localhost for external access
      # - NEXT_PUBLIC_BACKEND_HOST=localhost
      # - NEXT_PUBLIC_BACKEND_PORT=8000
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
    depends_on:
      - api

  api:
    build:
      context: ../
      dockerfile: ./services/api/Dockerfile
    env_file:
      - ../.env.local
    environment:
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_REGION=us-east-1
      - S3_BUCKET=aeon-dev-bucket
      - S3_FORCE_PATH_STYLE=true
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - localstack

  worker:
    build:
      context: ../
      dockerfile: ./services/worker/Dockerfile
    env_file:
      - ../.env.local
    environment:
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_REGION=us-east-1
      - S3_BUCKET=aeon-dev-bucket
      - S3_FORCE_PATH_STYLE=true
    depends_on:
      - redis
      - localstack

  # PostgreSQL removed - using Neon cloud database

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3.7
    environment:
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - "localstack:/var/lib/localstack"

volumes:
  localstack:

