services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7

  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile.api
    env_file:
      - .env.api
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: deployment/Dockerfile.worker
    env_file:
      - .env.worker
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env.web
    depends_on:
      - api

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - api

volumes:
  pgdata:
